<?php

/**
 * TO REDESIGN
 */

namespace App\web_socket;

require_once '../../vendor/autoload.php';

use App\models\GamesPvpModel;
use App\utilities\Jwt;
use App\models\UserModel;
use Ratchet\ConnectionInterface;
use Ratchet\MessageComponentInterface;

class Chess implements MessageComponentInterface
{
    private $clients;
    private UserModel $userModel;
    private GamesPvpModel $gamesPvpModel;
    public function __construct()
    {
        $this->clients = new \SplObjectStorage;
        $this->userModel = new UserModel();
        $this->gamesPvpModel = new GamesPvpModel();
        echo "Server Started\n";
    }

    public function onOpen(ConnectionInterface $conn)
    {

        // Store the new connection in $this->clients
        $this->clients->attach($conn);

        echo "New connection! ({$conn->resourceId})\n";
    }

    public function onMessage(ConnectionInterface $from, $msg)
    {

        $data = json_decode($msg); //decode the message
        $request = $data->request;
        $token = $data->jwt;

        $this->userModel->setId(Jwt::getPayload($token)['user_id']);
        $this->userModel->setStatus("online");

        switch ($request) {
            case 'home':
                $this->userModel->setId(Jwt::getPayload($token)['user_id']);
                $connectionId = $this->userModel->getLast_ConnectionId(); //need to disconnect the device if it exist in $this->clients

                foreach($this->clients as $client){
                    if($client->resourceId === $connectionId){
                        $client->send(json_encode(array(
                            'disconnect' => 'disconnect'
                        )));
                        echo "trovato connection id";
                        break;
                    }
                }
                echo $connectionId;
                $this->userModel->setLast_ConnectionId($from->resourceId);
                $this->userModel->updateConnectionId();
                break;

            case 'vsComputer':
                $fen = '"' . $data->fen . '"';
                $fileName = "$data->username.txt";
                $skill = $data->skill;

                $move = $this->getMove($fileName, $fen, $skill);
                $from->send(json_encode(array(
                    'move' => $move
                )));
                break;
            case 'vsPlayer':
                
            default:

                break;
        }
    }
    public function onClose(ConnectionInterface $conn)
    {
        $this->clients->detach($conn);
        $this->userModel->setStatus("offline");

        echo "Connection {$conn->resourceId} has disconnected\n";
    }

    public function onError(ConnectionInterface $conn, \Exception $e)
    {
    }
    /**
     * Executes a Python script with given arguments, reads the output file, deletes
     * the file, and returns the content as a string.
     * 
     * @param string fileName The name of the file that will be generated by the Python script and used
     * to store the output (i.e. the move made by the chess engine).
     * @param string fen FEN (Forsyth–Edwards Notation) is a standard notation for describing a
     * particular board position of a chess game. It describes the position of all pieces on the board,
     * which player has the move and castling availability
     * @param string skill The skill level of the chess engine being used.
     * 
     * @return string a string that represents the move played by the engine
     */
    private function getMove(string $fileName, string $fen, string $skill): string
    {
        $fileName = escapeshellcmd($fileName);
        $fen = escapeshellcmd($fen);
        $skill = escapeshellcmd($skill);

        exec("py ../python/main.py $fileName $fen $skill"); //execute the python script

        $file = fopen("../generated_files/$fileName", "r"); //open the file created by the script

        $move = fread($file, filesize("../generated_files/$fileName")); //assign to a variable the move

        unlink("../generated_files/$fileName"); //delete the file created by the python script

        return $move; //return the move generated

    }
}
