#1
SELECT COUNT(CodOp) AS numeroOpere, AnnoComposizione
FROM OPERE
GROUP BY Compositore
#2
SELECT COUNT(CodOp) AS 'Opere non rappresentate'
FROM OPERE
LEFT JOIN SPETTACOLI
ON OPERE.CodOp = SPETTACOLI.CodOp
WHERE OPERE.CodOp IS NOT NULL
#3
SELECT Nome
FROM CANTA
GROUP BY NOME ASC
HAVING COUNT(CodSP) > 1
#4
